build:
	g++ -std=c++17 -o largeint largeint.cpp main.cpp

run:
	./largeint

quick:
	g++ -std=c++17 -o largeint largeint.cpp main.cpp
	./largeint

clean:
	rm -f largeint

main:
	g++ -o test main.cpp
	./test
